/// AUTO GENERATED FILE ///
// src in       /webinterface/webcontent/
// generated by /webinterface/dstc.lua

#include <Arduino.h>

using namespace std;

int webContentSize = 5;
string webContent[5][2]={
  {"/espPinout.png","IGNORED FILE BY dstc.lua"},
  {"/index.html","<script src=\"/lzw.js\"></script><script>\nloadLzwContent(\"/test.html\",document.write)\n</script>"},
  {"/lzw.js","function de(b){\nvar a,e={},d=b.split(\"\"),c=f=d[0],g=[c],h=o=256;\nfor(b=1;b<d.length;b++)\na=d[b].charCodeAt(0),a=h>a?d[b]:e[a]?e[a]:f+c,g.push(a),c=a.charAt(0),e[o]=f+c,o++,f=a;\nreturn g.join(\"\")\n}\nfunction loadLzwContent(url,cb){\nfetch(url)\n.then(res=>res.text())\n.then(data=>{\ny=new Uint8Array(data)\no=\"\"\nfor (i=0;i<y.length;i++){\no += String.fromCharCode(y[i])\n}\ncb(de(o.replace(\"/\\\\0\",\"\\x00\").replace(\"\\\\\\\\\",\"\\\\\")))\n}\n)\n}"},
  {"/styles.css",""},
  {"/test.html",""} 
};

int findWebContent(string search) {
  for(int i = 0; i < webContentSize; i++){
    if (webContent[i][0] == search) {
      return i;
    }
  } 
  return -1;
}